set_property PACKAGE_PIN L16 [get_ports clock]
set_property PACKAGE_PIN R18 [get_ports reset]
set_property PACKAGE_PIN V12 [get_ports io_RD]
set_property PACKAGE_PIN T16 [get_ports {io_SW_IN[3]}]
set_property PACKAGE_PIN W13 [get_ports {io_SW_IN[2]}]
set_property PACKAGE_PIN P15 [get_ports {io_SW_IN[1]}]
set_property PACKAGE_PIN G15 [get_ports {io_SW_IN[0]}]
set_property PACKAGE_PIN W16 [get_ports io_TD]
set_property PACKAGE_PIN J15 [get_ports {io_GPIO[7]}]
set_property PACKAGE_PIN H15 [get_ports {io_GPIO[6]}]
set_property PACKAGE_PIN V13 [get_ports {io_GPIO[5]}]
set_property PACKAGE_PIN U17 [get_ports {io_GPIO[4]}]
set_property PACKAGE_PIN D18 [get_ports {io_GPIO[3]}]
set_property PACKAGE_PIN G14 [get_ports {io_GPIO[2]}]
set_property PACKAGE_PIN M15 [get_ports {io_GPIO[1]}]
set_property PACKAGE_PIN M14 [get_ports {io_GPIO[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports io_RD]
set_property IOSTANDARD LVCMOS33 [get_ports {io_SW_IN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_SW_IN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_SW_IN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_SW_IN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports io_TD]
set_property IOSTANDARD LVCMOS33 [get_ports {io_GPIO[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_GPIO[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_GPIO[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_GPIO[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_GPIO[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_GPIO[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_GPIO[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_GPIO[0]}]

create_clock -period 8.000 -name clock -waveform {0.000 4.000} [get_ports clock]
